modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
[[mods]]
modId="turned"
version="1.4.0"
displayName="Turned"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
A mod inspired by the steam game "Changed", mixed sightly with my Discord Server "Adapted" lore, who is a Roleplay based on a different timeline of Changed!
The mod focuses on having mostly transform-based mechanics and various NPCs/Monsters, Along with decorative and building blocks.
'''
[[dependencies.turned]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.turned]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"