/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.latexes;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class LatexModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public LatexModElements() {
		sounds.put(new ResourceLocation("latex", "computer_on"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "computer_on")));
		sounds.put(new ResourceLocation("latex", "dart_shot"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "dart_shot")));
		sounds.put(new ResourceLocation("latex", "puro_the_block_music"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "puro_the_block_music")));
		sounds.put(new ResourceLocation("latex", "burp"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "burp")));
		sounds.put(new ResourceLocation("latex", "robot_burp"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "robot_burp")));
		sounds.put(new ResourceLocation("latex", "death_beep"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "death_beep")));
		sounds.put(new ResourceLocation("latex", "robot_beep"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "robot_beep")));
		sounds.put(new ResourceLocation("latex", "gunshot"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "gunshot")));
		sounds.put(new ResourceLocation("latex", "gas_mask_wear"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "gas_mask_wear")));
		sounds.put(new ResourceLocation("latex", "transfur"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "transfur")));
		sounds.put(new ResourceLocation("latex", "deny_beep"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "deny_beep")));
		sounds.put(new ResourceLocation("latex", "approve_beep"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "approve_beep")));
		sounds.put(new ResourceLocation("latex", "click_noise"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "click_noise")));
		sounds.put(new ResourceLocation("latex", "rifle_shot"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "rifle_shot")));
		sounds.put(new ResourceLocation("latex", "tank_shot"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "tank_shot")));
		sounds.put(new ResourceLocation("latex", "silenced_shot"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "silenced_shot")));
		sounds.put(new ResourceLocation("latex", "shotgun-blast"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "shotgun-blast")));
		sounds.put(new ResourceLocation("latex", "latex_tune"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "latex_tune")));
		sounds.put(new ResourceLocation("latex", "armageddon"), new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "armageddon")));
		sounds.put(new ResourceLocation("latex", "the_only_thing_they_fear_is_you"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("latex", "the_only_thing_they_fear_is_you")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("latex").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == LatexModElements.ModElement.class)
						elements.add((LatexModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(LatexModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		LatexMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final LatexModElements elements;
		protected final int sortid;
		public ModElement(LatexModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
